version: '3.9'
services:
  cloudflare-ddns:
    image: ghcr.io/cchriso/cloudflare-ddns:latest # please use specific version tags in production, e.g., "2.0.0"
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /YOUR/PATH/HERE/config.json:/config.json
    restart: unless-stopped
