name: Build cloudflare-ddns Docker image (multi-arch)

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'README.md'
      - '*.md'
      - '**/*.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Extract version from Python file
        shell: bash
        run: echo "##[set-output name=version;]$(grep -oP '__version__ = "\K[^"]+' cloudflare-ddns.py)"
        id: extract_version
      
      - name: Check if version tag already exists
        shell: bash
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          echo "Checking if version $VERSION already exists..."
          
          # Check Docker Hub
          DOCKERHUB_EXISTS=$(curl -s "https://hub.docker.com/v2/repositories/cchriso/cloudflare-ddns/tags/$VERSION" | grep -o '"name"' || echo "")
          
          # Check GitHub Container Registry
          GHCR_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://ghcr.io/v2/cchriso/cloudflare-ddns/manifests/$VERSION")
          
          if [ ! -z "$DOCKERHUB_EXISTS" ] || [ "$GHCR_STATUS" = "200" ]; then
            echo "::error::Version $VERSION already exists in one or more registries. Please update the version in cloudflare-ddns.py before merging."
            exit 1
          else
            echo "Version $VERSION does not exist. Proceeding with build..."
          fi
        id: check_version
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            cchriso/cloudflare-ddns
            ghcr.io/cchriso/cloudflare-ddns
          sep-tags: ','
          flavor: |
            latest=false
          tags: |
            type=raw,enable=${{ steps.extract_branch.outputs.branch == 'master' }},value=latest
            type=raw,enable=${{ steps.extract_branch.outputs.branch == 'master' }},value=${{ steps.extract_version.outputs.version }}
            type=schedule
            type=ref,event=pr
            
      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/ppc64le,linux/s390x,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
